version: '3.6'

services:
  app:
    container_name: vaquinha-dev
    image: vaquinha-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    networks:
      - vaquinha-dev
    restart: always

networks:
  vaquinha-dev:
    driver: bridge
