version: '3.8'

services:
  app:
    container_name: vaquinha-dev
    image: vaquinha
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
